add sticky headers and optional height
ghostebony/svelte-virtual pull request #30
Opened 2023-04-22 11:44 UTC by wattsjs

made some changes locally to fit my needs - thought it may be useful 🙂

- add the ability to set specific items as sticky
- change `height` to optional, defaulting to 100%

2023-04-22 13:06 UTC, wattsjs commented
run prettier

2023-04-23 11:42 UTC, ghostebony requested changes
thanks for the contribution.
after these changes I think it will be ready to merge

2023-04-23 11:42 UTC, ghostebony commented on src/lib/list/List.svelte
> +	export let stickyIndicies: number[] = [];
fix the typo `stickyIndicies` to `stickyIndices`

2023-04-23 11:42 UTC, ghostebony commented on src/lib/list/List.svelte
> +		{#if stickyIndicies.length}
check `indexes` too:
```svelte
{#if stickyIndices.length && indexes.length}
```

2023-04-23 11:42 UTC, ghostebony commented on src/lib/list/List.svelte
> +				...stickyIndicies.filter((i) => i < (indexes?.[0] ?? 0))
```ts
...stickyIndices.filter((i) => i < indexes[0])
```

2023-04-23 11:42 UTC, ghostebony commented on src/lib/list/List.svelte
> +					<slot name="item" index={stickyIndex} />
add default template message like
```svelte
<slot name="item" {index}>Missing template</slot>
```

2023-04-23 12:34 UTC, wattsjs commented
Sounds great 👍

2023-04-23 12:35 UTC, wattsjs reviewed
lgtm

2023-04-23 12:52 UTC, ghostebony approved these changes

2023-04-23 12:58 UTC, merged